### ISSUE TITLE
 SlidingMenu

### ISSUE THREAD

**Issue by ghost** [Freelander/Android_Data#14]
SlidingMenu不建议使用是个什么鬼？“这个库已经被广泛使用, 可是到现在这个库已经被放弃了”---谁说的？

**Comment by manuchen** [comment]
安卓新版本已经加了新控件代替它了

**Comment by anonymouslh2** [comment]
你是指DrawerLayout吗？感觉还没有SlidingMenu好用呢

**Comment by manuchen** [comment]
是的。
